version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: web-javascript_nginx
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/files/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/public:/usr/share/nginx/html

  node:
    image: node:slim
    container_name: web-javascript_node
    tty: true
    working_dir: /app
    volumes:
      - ./app:/app
